name: Docs

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'

concurrency: ${{ github.ref }}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install packages
        run: yarn install --immutable

      - name: 🤡 Build Clown-ui
        run: yarn build

      - name: Build Storybook
        run: yarn storybook:build

      - name: 🚀 Deploy the website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./packages/storybook/docs
